src/reports/urls.py
from django.urls import path
from .views import (
    create_report_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view
)

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name = 'main'),
    path('save/', create_report_view, name = 'create-report'),
    path('upload/', csv_upload_view, name = 'upload'),
    path('from_file/', UploadTemplateView.as_view(), name = 'from-file'),
    path('<pk>/', ReportDetailView.as_view(), name = 'detail'),
    path('<pk>/pdf/', render_pdf_view, name = 'pdf'),
]

src/reports_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace = 'sales')),
    path('reports/', include('reports.urls', namespace = 'reports')),
    path('my_profile/', include('profiles.urls', namespace = 'profiles')),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/sales/urls.py
from django.urls import path
from .views import (
    home_view,
    SaleListView,
    SaleDetailView,
    sale_list_view,
    sale_detail_view
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name = 'home'),
    # path('list/', SaleListView.as_view(), name = 'list'),
    # path('sales/<pk>/', SaleDetailView.as_view(), name = 'detail'),
    path('sales/', sale_list_view, name = 'list'),
    path('sales/<pk>/', sale_detail_view, name = 'detail'),
]

src/reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse
# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length = 120)
    image = models.ImageField(upload_to = 'reports', blank = True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete = models.CASCADE)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return (str(self.name))

    class Meta:
        ordering = ('-created',)

src/reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

src/reports/views.py
from django.shortcuts import render, get_object_or_404
from profiles.models import Profile
from django.http import JsonResponse
from .utils import get_report_image
from .models import Report
from django.views.generic import ListView, DetailView, TemplateView
# xhtml2pdf
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

from sales.models import Sale, Position, CSV
from products.models import Product
from customers.models import Customer
import csv
from django.utils.dateparse import parse_date

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'reports/main.html'

class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'reports/detail.html'

class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reports/from_file.html'

@login_required
def csv_upload_view(request):
    print('file is being sent')
    
    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name = csv_file_name)
        
        if created:
            obj.csv_file = csv_file
            obj.save()

            with open(obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)
                reader.__next__() # skip the first row (column names)
                for row in reader:
                    # print(row, type(row))
                    transaction_id = row[1]
                    product = row[2]
                    quantity = int(row[3])
                    customer = row[4] 
                    date = parse_date(row[5])

                    try:
                        product_obj = Product.objects.get(name__iexact = product)
                    except Product.DoesNotExist:
                        product_obj = None

                    print(product_obj)

                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(name = customer)
                        salesman_obj = Profile.objects.get(user = request.user)
                        position_obj = Position.objects.create(product = product_obj, quantity = quantity, created = date) 

                        sale_obj, _ = Sale.objects.get_or_create(transaction_id = transaction_id, customer = customer_obj, salesman = salesman_obj, created = date)
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()
                return JsonResponse({'ex': False})
        else:
            return JsonResponse({'ex': True})


    return HttpResponse()

@login_required
def create_report_view(request):
    if is_ajax(request):
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        image = request.POST.get('image')

        img = get_report_image(image)

        author = Profile.objects.get(user = request.user)
        Report.objects.create(name = name, remarks = remarks, image = img, author = author)
        return JsonResponse({'msg': 'sent'})
    
    return JsonResponse({})


# helper function as is_ajax() is deprecated
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

@login_required
# from xhtml2pdf
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    obj = get_object_or_404(Report, pk = pk)
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if display
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

src/reports/templates/reports/detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.name}}
{% endblock title %}

{% block content %}
    {% if object.image %}
    <img src="{{object.image.url}}" class="img-fluid" alt="{{object.name}}">
    {% endif %}
    <br>
    <h3>Remarks</h3>
    <p>{{object.remarks}}</p>
    <hr>
    <p><b>Author: {{object.author.user.username}}</b></p>
    <p><b>Created: {{object.created}}</b></p>
{% endblock content %}

src/reports/templates/reports/from_file.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
upload sales files
{% endblock title %}

{% block content %}
    <h5>Upload your sales documents</h5>
    <br> 
    <div id="alert-box"> </div>
    <form id="my-dropzone" class="dropzone dz">
        {% csrf_token %}
        <div class="fallback">
            <input name="file" type="file" multiple />
        </div>
    </form>
{% endblock content %}

src/reports/templates/reports/main.html
{% extends 'base.html' %}

{% block title %}
    reports
{% endblock title %}

{% block content %}
reports
<hr>
{% for obj in object_list %}

    <div class="card mb-3">
        {% if obj.image %}
            <img src="{{obj.image.url}}" class="card-img-top" alt="{{obj.name}}">
        {% endif %}

        <div class="card-body">
            <h5 class="{{obj.name}}">Card title</h5>
            <p class="card-text">{{obj.remarks|truncatewords:2}}</p>
            <a href="{{obj.get_absolute_url}}" class="btn btn-primary">Details</a>
            <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger">PDF</a>
        </div>
    </div>

{% endfor %}
{% endblock content %}

src/reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>PDF {{obj.name}}</title>
  <style>
      .image {
          width: 100%;
          height: auto;
      }
  </style>
</head>
<body>
    <h1>{{obj.name}}</h1>
    <hr>
    <img src={{obj.image.path}} class="image">
    <br>
    <h3>Remarks</h3>
    <p>{{obj.remarks}}</p>
    <hr>
    <p><b>Author: {{obj.author.user.username}}</b></p>
    <p><b>Created: {{obj.created}}</b></p>
</body>
</html>